# =============进程=============
server:
  port: 8080

spring:
  # =============datasource=============
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: will
    password: will
    url: jdbc:mysql://192.168.1.3:3306/snippet?useUnicode=true&characterEncoding=utf-8&userSSL=false
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: ubuntu-master
      connection-timeout: 10000
mybatis:
  mapper-locations: classpath:mappers/*.xml
